## Neural Network from Scrach Code 

In [1]:
import numpy as np

In [2]:
def sigmoid (x):
    return 1.0/(1+ np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x *(1.0-x)

In [8]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        #print("inputs \n", self.input)
        #print () # x*theta    x = 4*3
        self.weights1 = np.random.rand(self.input.shape[1],4) # 0 : 1 ==> [0.5,0.88,0.25,0.5]
        #print('weights1 \n', self.weights1)
        #print()
        self.weights2 = np.random.rand(4,1)
        #print('weights2 \n',self.weights2)
        #print()
        self.y = y
        #print('y  \n', self.y)
        #print ()
        self.output = np.zeros (self.y.shape) # h(x) ==> predicted value 
        # print('output In', self.output)
        # print ()
    
    def feedfforward(self):
        self.layer1 = sigmoid(np.dot(self.input,self.weights1))
        #print(' layer 1 \n',self.layer1)
        #print()
        self.output= sigmoid(np.dot(self.layer1, self.weights2))
        #print( 'output \n',self.output)
        #print()
    def backprop(self):
       # application of the chain rule to find derivative of the Loss function with
        d_weights2 = np.dot(self.layer1.T,(2*(self.y - self.output)*sigmoid_derivative(self.output)))
        #print('d_weights2 \n', d_weights2)
        #print()
        d_weights1= np.dot(self.input.T,
                               (np.dot(d_weights2,
                                       self.weights2.T)*sigmoid_derivative (self. layer1)))
        # print('d weigh ts1 \n',d_weights1)
        # print()
    #update the weights with the derivative (slope) of the Loss function
        self.weights1 += d_weights1
        self.weights2 += d_weights2

In [9]:
X = np.array( [[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])

y = np.array([[0],
            [1],
            [1],
            [0]])

In [10]:
nn = NeuralNetwork(X,y)

for i in range(100):
    nn.feedfforward()
    nn.backprop()
    # print('---------------------------')
print(nn.output)

d_weights2 
 [[-0.32771741 -0.24218813 -0.30246798 -0.29502449]
 [-0.3844833  -0.28700029 -0.35450179 -0.34470548]
 [-0.36433094 -0.27346112 -0.33631698 -0.32572836]
 [-0.37229088 -0.27972994 -0.34178065 -0.3329499 ]]



ValueError: non-broadcastable output operand with shape (4,1) doesn't match the broadcast shape (4,4)